apiVersion: v1
kind: ConfigMap
metadata:
  name: example-app-config
  namespace: example-app-new
data:
  application-production.properties: |
    application.name=app-svc-notification
    server.port=8082
    application.version={{DEPLOY_ENV}}-v1
    application.groups=ogs-core-apps
    server.servlet.context-path=/
    management.endpoints.web.base-path=/manage-v1
    management.endpoints.web.exposure.include=*
    management.endpoint.prometheus.enabled=true
    management.metrics.export.prometheus.enabled=true
    management.endpoint.restart.enabled=true
    management.endpoint.refresh.enabled=true
    management.endpoint.web.exposure.inculde=info,refresh,keepalive
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-app-deployment
  namespace: example-app-new
  labels:
    app: example-app
spec:
  selector:
    matchLabels:
      app: example-app
  template:
    metadata:
      labels:
        app: example-app
      annotations:
        "sidecar.jaegertracing.io/inject": with-sampling
    spec:
      volumes:
      - name: example-app-config-store
        configMap:
          name: example-app-config
      containers:
      - name: example-app-container
        image: example-app:1.0-SNAPSHOT
        ports:
        - containerPort: 8082
        volumeMounts:
        - mountPath: "/work/config/"
          name: example-app-config-store
        env:
        - name: JAEGER_ENDPOINT
          value: http://with-sampling-collector.jaeger-operator:14268/api/traces
        - name: SPRING_PROFILES_ACTIVE
          value: production
        - name: KAFKA_CONFIG_PATH
          value: /work/config/
        - name: SPRING_CONFIG_LOCATION
          value: /work/config/
---
apiVersion: v1
kind: Service
metadata:
  name: example-app-service
  namespace: example-app-new
spec:
  type: NodePort
  selector:
    app: example-app
  ports:
  - protocol: TCP
    port: 8082
    targetPort: 8082
    nodePort: 32500

